version: '3.9'

services:
    app:
        build:
            context: ../
            dockerfile: ./docker/deno/dockerfile
        volumes:
            - ../:/app
        ports:
            - 8080:8080