FROM denoland/deno:1.18.2

# 8080ポート開けたいので無視
# The port that your application listens to.
# EXPOSE 1993

WORKDIR /app

# bundleしたいので無視
# Prefer not to run as root.
# USER deno

# Cache the dependencies as a layer (the following two steps are re-run only when deps.ts is modified).
# Ideally cache deps.ts will download and compile _all_ external files used in main.ts.
COPY ./deno/deps.ts ./deno/
RUN deno cache ./deno/deps.ts

# These steps will be re-run upon each file change in your working directory:
ADD . .

# Compile the main app so that it doesn't need to be compiled each startup/entry.
RUN deno cache ./deno/main.jsx

CMD ["run", "--watch", "--allow-net", "--allow-read", "./deno/main.jsx"]